version: '3.4'

services:
  football.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "53203:80"
      - "53204:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 512M
    networks:
      backend:
        aliases:
           - api.development.fxstreet-interview.com
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    labels:
      com.microsoft.visual-studio.project-name: "Postgres"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M
        reservations:
          cpus: "1"
          memory: 1024M
    volumes:
      - "${USERPROFILE}/postgres/fxstreet:/var/lib/postgresql"
      - "${USERPROFILE}/postgres/fxstreet/data:/var/lib/postgresql/data"
    networks:
      backend:
         aliases:
            - postgres.development.fxstreet-interview.com
    ports:
      - 6543:5432
    environment:
      - POSTGRES_DB=football
      - POSTGRES_USER=fxstreet
      - POSTGRES_PASSWORD=GaCc8N762Bm
      
networks:
    backend:
       driver: bridge
       ipam:
          driver: default
          config:
             - subnet: 172.16.238.0/24